language: python
python:
  - "2.6"
  - "2.7"
install:
  - python setup.py develop
  - pip install webob webtest coverage
  - sudo apt-get update
  - sudo apt-get install python27-profiler python26-profiler
script: nosetests